- hosts : namenode
  gather_facts : no
  vars_prompt :
          - name : ndir
            prompt : "Enter Name Node Directory Name "
            private : no

          - name  : nip
            prompt : " Enter the Name Node IP: "
            private : no 

  tasks : 
        - name  : Java Software
          shell  : "rpm -ivh jdk-8u171-linux-x64.rpm"
          ignore_errors : True

                  
        - name : Hadoop Software
          shell : "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"
          ignore_errors : True

        - name: Creating Name Node Directory
          file:
                path: "{{ ndir }}"
                state: directory

        - name: Configuring hdfs-site.xml
          blockinfile:
                path: /etc/hadoop/hdfs-site.xml
                insertafter: "<configuration>"
                block: 
                 <property>
                 <name>dfs.name.dir</name>
                 <value>{{ ndir }}</value>
                 </property>


        - name: Configuring core-site.xml file
          blockinfile:
                path: /etc/hadoop/core-site.xml
                insertafter: "<configuration>"
                block:
                        <property>
                        <name>fs.default.name</name>
                        <value>hdfs://{{ nip }}:9001</value>
                        </property>
         
        - name: Formatting Name Node Directory
          shell: "echo Y | hadoop namenode -format"
          ignore_errors: True
    

        - name: Starting hadoop Name Node services
          command: "hadoop-daemon.sh start namenode"
          ignore_errors: True
      
    
        - name: Checking status of Name Node Services
          shell: "jps"
          ignore_errors: True

