- hosts: haproxy
  tasks:
   - name: "Installing HAPROXY Software"
     package:
      name: "haproxy"
      state: present
   - name: "Copying the HAPROXY Config file"
     template:
      src: haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
   - firewalld:
      port: 8080/tcp
      state: enabled
      permanent: yes
      immediate: yes
   - name: "Starting the Proxy"
     service: 
      name: haproxy
      state: restarted